# Working with numpy basics

In [1]:
import numpy as np 

In [2]:
a = np.array([1,2,3,4])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [3]:
b = np.array([[1],[2],[3],[4]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [4]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [5]:
# we can also create zeros , ones , custome arrays

a = np.zeros((3,3))
print(a)

b = np.ones((3,3))
print(b)

# creating custome matrix
c = np.full((3,2),5) 
print(c)

# also we can have identity matrix
d = np.eye(4)
print(d)

# Random Matrix
rand = np.random.random((2,3))

print(rand)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[5 5]
 [5 5]
 [5 5]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 0.18877888  0.56030157  0.59579036]
 [ 0.79013595  0.23575738  0.16562157]]


In [6]:
print(rand[ : ,1])

[ 0.56030157  0.23575738]


In [7]:
rand[1,1:] = 1.654
print(rand)

[[ 0.18877888  0.56030157  0.59579036]
 [ 0.79013595  1.654       1.654     ]]


In [8]:
print(rand.dtype)

float64


In [9]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.sqrt(x))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [10]:
# Matrix Multiplicstion / dot product

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [11]:
# Multiplication of vectors => scalar(output)
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

print(np.dot(a,b))
print(np.sum(a))

30
10


In [12]:
print(x)


[[1 2]
 [3 4]]


In [13]:
print(np.sum(x,axis=0))

[4 6]


In [14]:
print(a)
b=b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [15]:
print(np.stack((a,b),axis=0))

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [16]:
a = np.stack((a,b),axis=0)

In [17]:
a = a.reshape((4,2))
print(a)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


In [18]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [20]:
np.random.shuffle(a)
print(a)

[11 13  8  5 12  9 14 10  6  7]


In [21]:
a = np.random.rand(2,3)
print(a)

[[ 0.77796207  0.42840647  0.93547749]
 [ 0.88518106  0.90538239  0.03645945]]


In [22]:
b = np.random.randn(2,3)
print(b)

[[ 1.03354775  0.37624497  1.19922896]
 [-0.69133031  0.47832972 -0.77743015]]


In [23]:
c = np.random.randint(5,10,3)
print(c)

[6 9 9]


In [24]:
d = np.random.choice([5,10,3,11,8,0,5])
print(d)

8


# Matrix multiplication

In [25]:
x = np.array([[2,4,3],[5,7,11],[32,6,7]])
y = np.array([[10,20,30],[11,22,33],[100,200,300]])

print(x.shape)
print(y.shape)

print(x)
print(y)

(3, 3)
(3, 3)
[[ 2  4  3]
 [ 5  7 11]
 [32  6  7]]
[[ 10  20  30]
 [ 11  22  33]
 [100 200 300]]


In [26]:
prod = np.dot(x,y)
print(prod)

[[ 364  728 1092]
 [1227 2454 3681]
 [1086 2172 3258]]


### Eliment wise multiplication

In [27]:
x = np.array([[2,4,3],[5,7,11],[32,6,7]])
# this will create an identity matrix
y = np.eye(3)

print(x)
y = y*2
y +=1
print(y)

[[ 2  4  3]
 [ 5  7 11]
 [32  6  7]]
[[ 3.  1.  1.]
 [ 1.  3.  1.]
 [ 1.  1.  3.]]


In [28]:
print(x*y)

[[  6.   4.   3.]
 [  5.  21.  11.]
 [ 32.   6.  21.]]


### Norms

In [29]:
x = np.array([-5,2,10])

# predefine as lp1,lp2and lpinf
lp2 = np.linalg.norm(x)
print(lp2)

11.3578166916


In [30]:
# this will give the sum of the array
lp1 = np.linalg.norm(x,ord=1)
print(lp1)

17.0


In [31]:
# this will give the hiegest among the array no matter (-)ve or (+)ve.
lpinf = np.linalg.norm(x,ord=np.inf)
print(lpinf)

10.0


### Broadcasting
- allows you to play with list or perform actions on same.
- also with the matrix also.

In [32]:
l = [1,2,3,4]
l += 1
print(l)

TypeError: 'int' object is not iterable

In [33]:
l = [1,2,3,4]
l = np.array(l)
l += 1
print(l)

[2 3 4 5]


In [34]:
l = [1,2,3,4]
l = np.array(l)
l += 1
print(l)

[2 3 4 5]


In [35]:
l = [[1,2,3,4],[3,5,7,6]]
l = np.array(l)
l = l**2
print(l)

[[ 1  4  9 16]
 [ 9 25 49 36]]
